# Indicates compatibility version with lifecycle
api = "0.7"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "nncdevel-io/buildpack-application-config-environment-variable-labels"
  name = "Export spring application configuration Environment Variable to labels"
  version = "1.1.0"
  keywords = ["java", "environment variable"]
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]

[[metadata.configurations]]
name        = "BP_APP_CONFIG_ENVIRONMENT_VARIABLE_LABEL_NAME"
description = "Export target OCI image label key"
default     = "io.nncdevel.buildpacks.application-config.environment-variables"
build       = true

[[metadata.configurations]]
name        = "BP_APP_CONFIG_ENVIRONMENT_VARIABLE_TARGET_PATTERNS"
description = "Target file glob patterns."
default     = "BOOT-INF/classes/application.properties,BOOT-INF/classes/application.ya?ml,WEB-INF/classes/application.properties,WEB-INF/classes/application.ya?ml"
build       = true

# The list of stacks that the buildpack itself is compatible with
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "*"
